on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'

      - name: Build
        run: |
          ./build.sh ubuntu24.04
          ./build.sh ubuntu24.04-aarch64
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            output/darwin-ubuntu24.04.artifactbundle.zip
            output/darwin-ubuntu24.04-aarch64.artifactbundle.zip
